# -*- coding: utf-8 -*-
"""Multi-Emotion Text Classifie

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgp7chn7FKI4wn2SRUjl3W256-zK3iCU
"""



# 📦 Install required libraries
print("📦 Installing AI libraries...")

try:
    import transformers
    from PIL import Image
    print("✅ Libraries already installed!")
except ImportError:
    !pip install transformers torch pillow requests
    print("✅ Libraries installed successfully!")

# Import everything we need
from transformers import pipeline # import ML models
import matplotlib.pyplot as plt # build dashboards and visualizations
from collections import Counter # statistics
import pandas as pd # manages datasets
import numpy as np # mathematics
from PIL import Image # work with images
import requests # fetch information from the internet
from io import BytesIO
import warnings
warnings.filterwarnings('ignore')

print("🎉 All set! Let's build some AI magic!")
print("🧠 We now have access to state-of-the-art AI models trained by Google, Facebook, and more!")



# 🧠 Load Advanced Emotion Classification Model
print("🤖 Loading advanced emotion AI model...")
print("🎓 This model was trained on millions of text examples to understand human emotions!")
print("⏳ First load takes ~30 seconds as we download the model...")

emotion_classifier = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    device=-1  # Use CPU (works on all systems)
)

print("✅ Advanced emotion AI model loaded successfully!")
print("💡 This model can detect: Joy, Sadness, Anger, Fear, Surprise, and Neutral emotions!")
print("🎯 Accuracy: ~94% on standard emotion datasets!")

result = emotion_classifier("We are having a lot of fun demystifying AI together!")

result

# 🧪 Test the emotion classifier with diverse examples
print("🧪 TESTING PHASE: Let's see what our advanced AI can detect!")
print("="*60)

# Carefully crafted examples to showcase different emotions
test_examples = [
    "I just got promoted at work! This is the best day ever!",  # Joy
    "I lost my phone and all my photos are gone... I'm heartbroken!",  # Sadness
    "This service is terrible! I've been waiting for 2 hours!",  # Anger
    "I'm really nervous about the presentation tomorrow",  # Fear
    "I can't believe they chose me for the scholarship!",  # Surprise
    "The meeting is scheduled for 3 PM in conference room B",  # Neutral
    "I'm absolutely devastated by this news",  # Sadness
    "This is so frustrating! Nothing is working properly!"  # Anger
]

print("\n🎭 Testing 8 different emotional examples:")
print("-" * 50)

results = []
emotion_emojis = {
    'joy': '😊',
    'sadness': '😢',
    'anger': '😠',
    'fear': '😨',
    'surprise': '😮',
    'neutral': '😐'
}

for i, text in enumerate(test_examples, 1):
    result = emotion_classifier(text)
    emotion = result[0]['label'].lower()
    confidence = result[0]['score']

    # Get appropriate emoji
    emoji = emotion_emojis.get(emotion, '🤔')

    print(f"{i}. {emoji} {emotion.upper()} ({confidence:.1%})")
    print(f"   📝 Text: {text}")
    print()

    results.append({'text': text, 'emotion': emotion, 'confidence': confidence})

print("🎯 Wow! Our AI can understand the nuances of human emotions!")



# 📊 Create Professional Business Dashboard
print("📊 CREATING BUSINESS INTELLIGENCE DASHBOARD")
print("="*55)

# Analyze customer feedback with emotions
customer_feedback = [
    "This product exceeded all my expectations! Amazing quality! 🌟",
    "Terrible customer service. Very disappointed with my purchase 😠",
    "Good value for money. Does what it's supposed to do.",
    "I'm so happy with this purchase! Best decision ever! 😊",
    "Overpriced for what you get. Found better alternatives elsewhere.",
    "Fast shipping and great packaging! Very impressed 📦",
    "The setup instructions were confusing and frustrating 😤",
    "Highly recommend! Outstanding quality and design! ⭐",
    "Average product, nothing special but works fine.",
    "Wow! This completely solved my problem! So grateful! 🙏",
    "Product broke after one week. Quality control issues 💔",
    "Surprised by how good this is for the price! Great buy 👍"
]

print("🔄 Processing customer feedback through emotion AI...")

for i, text in enumerate(customer_feedback, 1):
    result = emotion_classifier(text)
    emotion = result[0]['label'].lower()
    confidence = result[0]['score']

    # Get appropriate emoji
    emoji = emotion_emojis.get(emotion, '🤔')

    print(f"{i}. {emoji} {emotion.upper()} ({confidence:.1%})")
    print(f"   📝 Text: {text}")
    print()

    results.append({'text': text, 'emotion': emotion, 'confidence': confidence})

# Analyze all feedback
feedback_results = []
for feedback in customer_feedback:
    result = emotion_classifier(feedback)
    emotion = result[0]['label'].lower()
    confidence = result[0]['score']

    feedback_results.append({
        'feedback': feedback,
        'emotion': emotion,
        'confidence': confidence
    })

# Count emotions
emotion_counts = Counter([r['emotion'] for r in feedback_results])
total_feedback = len(feedback_results)

print(f"✅ Analyzed {total_feedback} pieces of customer feedback!")
print("\n📈 EMOTION BREAKDOWN:")
for emotion, count in emotion_counts.most_common():
    percentage = (count / total_feedback) * 100
    emoji = emotion_emojis.get(emotion, '🤔')
    print(f"   {emoji} {emotion.title()}: {count} ({percentage:.1f}%)")

# 🎨 Create Professional Visualizations
print("\n🎨 Creating professional business visualizations...")

# Set up the plotting style
plt.style.use('default')
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('🏢 AI-Powered Customer Feedback Analysis Dashboard', fontsize=20, fontweight='bold', y=0.98)

# Color scheme for emotions
emotion_colors = {
    'joy': '#2ECC71',      # Green
    'sadness': '#3498DB',   # Blue
    'anger': '#E74C3C',     # Red
    'fear': '#9B59B6',      # Purple
    'surprise': '#F39C12',  # Orange
    'neutral': '#95A5A6'    # Gray
}

# 1. Pie Chart - Emotion Distribution
emotions = list(emotion_counts.keys())
counts = list(emotion_counts.values())
colors = [emotion_colors.get(emotion, '#BDC3C7') for emotion in emotions]

wedges, texts, autotexts = ax1.pie(counts, labels=[e.title() for e in emotions],
                                   autopct='%1.1f%%', colors=colors, startangle=90)
ax1.set_title('💭 Customer Emotion Distribution', fontsize=14, fontweight='bold', pad=20)

# 2. Bar Chart - Emotion Counts
bars = ax2.bar(emotions, counts, color=colors, alpha=0.8, edgecolor='black', linewidth=0.5)
ax2.set_title('📊 Emotion Frequency Analysis', fontsize=14, fontweight='bold', pad=20)
ax2.set_xlabel('Emotions', fontweight='bold')
ax2.set_ylabel('Number of Reviews', fontweight='bold')
ax2.tick_params(axis='x', rotation=45)

# Add value labels on bars
for bar in bars:
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height + 0.05,
             f'{int(height)}', ha='center', va='bottom', fontweight='bold')

# 3. Confidence Score Distribution
confidences = [r['confidence'] for r in feedback_results]
ax3.hist(confidences, bins=10, color='#3498DB', alpha=0.7, edgecolor='black')
ax3.set_title('🎯 AI Prediction Confidence Scores', fontsize=14, fontweight='bold', pad=20)
ax3.set_xlabel('Confidence Score', fontweight='bold')
ax3.set_ylabel('Frequency', fontweight='bold')
ax3.axvline(np.mean(confidences), color='red', linestyle='--', linewidth=2,
            label=f'Average: {np.mean(confidences):.1%}')
ax3.legend()

# 4. Business Impact Metrics
positive_emotions = ['joy', 'surprise']
negative_emotions = ['sadness', 'anger', 'fear']
neutral_emotions = ['neutral']

positive_count = sum(emotion_counts.get(e, 0) for e in positive_emotions)
negative_count = sum(emotion_counts.get(e, 0) for e in negative_emotions)
neutral_count = sum(emotion_counts.get(e, 0) for e in neutral_emotions)

categories = ['Positive\nExperience', 'Negative\nExperience', 'Neutral\nExperience']
values = [positive_count, negative_count, neutral_count]
colors_impact = ['#2ECC71', '#E74C3C', '#95A5A6']

bars_impact = ax4.bar(categories, values, color=colors_impact, alpha=0.8, edgecolor='black')
ax4.set_title('💼 Business Impact Overview', fontsize=14, fontweight='bold', pad=20)
ax4.set_ylabel('Number of Customers', fontweight='bold')

# Add percentage labels
for i, bar in enumerate(bars_impact):
    height = bar.get_height()
    percentage = (height / total_feedback) * 100
    ax4.text(bar.get_x() + bar.get_width()/2., height + 0.1,
             f'{int(height)}\n({percentage:.1f}%)', ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.show()

print("\n📈 BUSINESS INSIGHTS SUMMARY:")
print(f"   📊 Total Reviews Analyzed: {total_feedback}")
print(f"   😊 Positive Experiences: {positive_count} ({positive_count/total_feedback*100:.1f}%)")
print(f"   😠 Negative Experiences: {negative_count} ({negative_count/total_feedback*100:.1f}%)")
print(f"   😐 Neutral Experiences: {neutral_count} ({neutral_count/total_feedback*100:.1f}%)")
print(f"   🎯 Average AI Confidence: {np.mean(confidences):.1%}")

# Business recommendations
if positive_count > negative_count:
    print("\n✅ RECOMMENDATION: Overall positive sentiment! Focus on maintaining quality.")
elif negative_count > positive_count:
    print("\n⚠️ RECOMMENDATION: Address negative feedback urgently. Investigate common issues.")
else:
    print("\n📊 RECOMMENDATION: Mixed sentiment. Analyze specific feedback for improvement areas.")

print("\n🎉 Professional dashboard created! This is portfolio-ready! 🌟")
